version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package_ecosystem: "submodules"
    directory: .
    schedule:
      interval: "daily"
