name: Microsoft Security DevOps Analysis

on:
  workflow_dispatch:

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@preview
      id: msdo
      
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
